### PR TITLE
Add InstantPocketbase type with custom Serializable

### PR DESCRIPTION
**Pull request by sergeypdev**
I wanted to have something like this for my custom types, but I thought it would be great to have on the BaseModel for `created` and `updated` as well.

Disclaimer: I wasn't able to test properly, not sure if my set up is wrong or if tests actually failed.

### CODE REVIEW

**Comment by agrevster** [comment]
It looks good! I've had better instant serialization on the to-do list for a while now. I appreciate the contribution. 

Unfortunately, I haven't gotten around to writing solid test documentation, but I'll get around to that soon-ish.
I'll merge as soon as Kotlin supports Xcode 15 for multiplatform builds.

**Comment by sergeypdev** [comment]
@agrevster if you're talking about [this issue](https://youtrack.jetbrains.com/issue/KT-60230), then it looks like it's already fixed.

**Comment by agrevster** [comment]
I saw that, but I'm also waiting on the fix for [another issue](https://youtrack.jetbrains.com/issue/KT-62215/Serialization-Native-IllegalArgumentException-No-container-found-for-type-parameter-caused-by-serializing-generic-classes-with-a) to be added to a stable Kotlin version.

**Comment by shalom-aviv** [comment]
> I saw that, but I'm also waiting on the fix for [another issue](https://youtrack.jetbrains.com/issue/KT-62215/Serialization-Native-IllegalArgumentException-No-container-found-for-type-parameter-caused-by-serializing-generic-classes-with-a) to be added to a stable Kotlin version.

Seems already fixed ;)

**Comment by agrevster** [comment]
Screenshot 2024-01-23 at 8 08 09 AM

**Pull request merged**
